version: '3'
services:
  toy-celery-broker-backend:
    image: redis
    ports:
      - '6379:6379'

  toy-celery-beat:
    build: .
    image: jwplayer/toy-celery:local
    volumes:
      - ./:/srv/
    environment:
      - RUN_MODE=beat

  toy-celery-flower:
    build: .
    image: jwplayer/toy-celery:local
    volumes:
      - ./:/srv/
    environment:
      - RUN_MODE=flower
    ports:
      - '5555:5555'
    command: sh -c 'sleep 5; make run'
